// Word banks by difficulty. Pure data — shared by web and terminal.
// `easy`   : short, extremely common words (fast to type, low finger travel)
// `medium` : common everyday words, 6+ letters
// `hard`   : longer, less common, tricky spelling / awkward letter combinations

export const WORD_BANKS = {
  easy: [
    'the', 'and', 'you', 'that', 'was', 'for', 'are', 'with', 'his', 'they',
    'this', 'have', 'from', 'one', 'had', 'word', 'but', 'not', 'what', 'all',
    'were', 'when', 'your', 'can', 'said', 'there', 'use', 'each', 'she', 'how',
    'their', 'will', 'other', 'about', 'out', 'many', 'then', 'them', 'these', 'some',
    'her', 'would', 'make', 'like', 'him', 'into', 'time', 'has', 'look', 'two',
    'more', 'day', 'did', 'get', 'come', 'made', 'may', 'part', 'over', 'new',
    'sound', 'take', 'only', 'little', 'work', 'know', 'place', 'year', 'live', 'back',
    'give', 'most', 'very', 'good', 'man', 'think', 'say', 'help', 'up', 'down',
    'off', 'run', 'walk', 'jump', 'big', 'red', 'hot', 'top', 'box', 'cup',
    'dog', 'cat', 'sun', 'car', 'bed', 'cut', 'old', 'few', 'six', 'ten',
    'now', 'end', 'far', 'ago', 'air', 'arm', 'art', 'bad', 'bag', 'ball',
    'base', 'bell', 'bird', 'blue', 'boat', 'body', 'book', 'both', 'bus', 'buy',
    'call', 'calm', 'card', 'care', 'case', 'city', 'club', 'cold', 'cook', 'cool',
    'cost', 'dark', 'deep', 'desk', 'dish', 'door', 'draw', 'dream', 'drink', 'drive',
    'drop', 'dry', 'east', 'easy', 'edge', 'fall', 'farm', 'fast', 'feel', 'feet',
    'fill', 'find', 'fine', 'fire', 'fish', 'flag', 'flat', 'floor', 'food', 'foot',
    'form', 'four', 'free', 'fresh', 'fruit', 'full', 'fun', 'game', 'gate', 'gift',
    'glad', 'glass', 'goal', 'gold', 'grass', 'gray', 'green', 'grow', 'half', 'hand',
    'hang', 'hard', 'hat', 'head', 'hear', 'heat', 'hill', 'hold', 'hope', 'hour',
    'huge', 'idea', 'inch', 'iron', 'keep', 'key', 'kind', 'king', 'lake', 'lamp',
    'land', 'last', 'late', 'lawn', 'leaf', 'left', 'leg', 'lend', 'life', 'light',
    'line', 'lion', 'lip', 'lock', 'long', 'lost', 'lot', 'loud', 'low', 'luck',
    'mail', 'main', 'mark', 'meal', 'meat', 'meet', 'mile', 'milk', 'mind', 'mix',
    'moon', 'move', 'mud', 'name', 'near', 'neck', 'nest', 'news', 'nice', 'node',
    'noon', 'nose', 'note', 'oak', 'oil', 'open', 'our', 'oven', 'pack', 'page',
    'pain', 'pair', 'park', 'pass', 'past', 'path', 'pen', 'pet', 'pick', 'pink',
    'plan', 'plant', 'play', 'plot', 'plus', 'pond', 'pool', 'poor', 'pot', 'pull',
    'push', 'race', 'rain', 'read', 'rest', 'rice', 'rich', 'ride', 'ring', 'rise',
    'road', 'rock', 'roof', 'room', 'root', 'rope', 'rose', 'row', 'rub', 'rug',
    'rule', 'rush', 'safe', 'sail', 'salt', 'sand', 'save', 'sea', 'seat', 'seed',
    'sell', 'send', 'shy', 'sick', 'side', 'sign', 'silk', 'sing', 'sit', 'size',
    'skin', 'sky', 'sleep', 'slow', 'small', 'snow', 'soap', 'sock', 'soft', 'song',
    'soon', 'sort', 'soup', 'spin', 'star', 'stay', 'step', 'stop', 'sweet', 'swim',
    'tail', 'talk', 'tall', 'tank', 'tape', 'task', 'team', 'tell', 'tent', 'test',
    'thin', 'tidy', 'tiny', 'tire', 'toe', 'told', 'tone', 'tool', 'tooth', 'toss',
    'town', 'toy', 'tree', 'trip', 'true', 'tube', 'tune', 'turn', 'twin', 'type',
    'van', 'vast', 'view', 'wall', 'warm', 'wash', 'wave', 'wax', 'weak', 'wear',
    'week', 'well', 'west', 'wet', 'wide', 'wild', 'win', 'wind', 'wine', 'wing',
    'wise', 'wish', 'wolf', 'wood', 'wool', 'worm', 'yard', 'yes', 'yet', 'zone',
    'zoo',
  ],
  medium: [
    'people', 'because', 'through', 'between', 'another', 'around', 'important', 'children', 'different', 'together',
    'thought', 'always', 'something', 'question', 'example', 'business', 'without', 'against', 'nothing', 'everyone',
    'sometimes', 'change', 'family', 'friend', 'system', 'program', 'problem', 'company', 'number', 'group',
    'follow', 'begin', 'water', 'science', 'country', 'weather', 'measure', 'increase', 'decision', 'remember',
    'consider', 'continue', 'possible', 'position', 'complete', 'develop', 'general', 'special', 'natural', 'certain',
    'perhaps', 'himself', 'kitchen', 'evening', 'morning', 'history', 'picture', 'machine', 'account', 'freedom',
    'journey', 'library', 'quality', 'purpose', 'section', 'similar', 'station', 'teacher', 'village', 'welcome',
    'balance', 'capital', 'absolute', 'achieve', 'address', 'advance', 'already', 'amount', 'analysis', 'ancient',
    'answer', 'appear', 'approach', 'argument', 'arrive', 'article', 'attempt', 'attention', 'audience', 'author',
    'available', 'average', 'basically', 'beautiful', 'become', 'bedroom', 'believe', 'benefit', 'besides', 'beyond',
    'breakfast', 'breathe', 'brother', 'building', 'capture', 'careful', 'category', 'central', 'century', 'certainly',
    'challenge', 'champion', 'chapter', 'character', 'choice', 'citizen', 'classic', 'collect', 'college', 'combine',
    'comfort', 'command', 'comment', 'committee', 'common', 'community', 'compare', 'computer', 'concern', 'condition',
    'confirm', 'connect', 'contact', 'contain', 'content', 'contract', 'control', 'convince', 'correct', 'courage',
    'creative', 'culture', 'current', 'customer', 'declare', 'decrease', 'deliver', 'describe', 'deserve', 'despite',
    'diamond', 'digital', 'direction', 'disagree', 'discover', 'discuss', 'distance', 'distant', 'document', 'downtown',
    'dramatic', 'economy', 'educate', 'election', 'electric', 'elephant', 'emotion', 'empire', 'employ', 'energy',
    'engine', 'english', 'enough', 'entire', 'episode', 'equally', 'escape', 'especial', 'establish', 'estimate',
    'evidence', 'exchange', 'exciting', 'exercise', 'expand', 'expect', 'explain', 'explore', 'express', 'extreme',
    'factory', 'failure', 'familiar', 'fantastic', 'favorite', 'feature', 'federal', 'feeling', 'fiction', 'finally',
    'finger', 'finish', 'flavor', 'flexible', 'foreign', 'forever', 'forget', 'fortune', 'forward', 'frequent',
    'friendly', 'function', 'furniture', 'gallery', 'generous', 'gentle', 'genuine', 'gesture', 'gigantic', 'gradual',
    'grateful', 'gravity', 'greater', 'grocery', 'guarantee', 'hallway', 'handful', 'happen', 'happiness', 'hardware',
    'healthy', 'heaven', 'heavy', 'holiday', 'honest', 'horizon', 'however', 'hundred', 'husband', 'imagine',
    'impact', 'improve', 'include', 'indeed', 'industry', 'initial', 'inspire', 'instead', 'intense', 'interest',
    'internal', 'invite', 'involve', 'justice', 'kingdom', 'knowledge', 'language', 'largely', 'laughter', 'leader',
    'learning', 'lecture', 'leisure', 'license', 'lifetime', 'likewise', 'limited', 'listen', 'literature', 'location',
    'magazine', 'magical', 'maintain', 'majority', 'manager', 'mankind', 'manner', 'marriage', 'massive', 'material',
    'medical', 'medium', 'meeting', 'member', 'memory', 'mention', 'message', 'midnight', 'million', 'mineral',
    'minute', 'mistake', 'mixture', 'modern', 'moment', 'monitor', 'monthly', 'mountain', 'movement', 'musician',
    'mystery', 'nearby', 'necklace', 'network', 'neither', 'nervous', 'never', 'notice', 'novel', 'nowhere',
    'numeral', 'obvious', 'ocean', 'offer', 'office', 'official', 'often', 'ongoing', 'operate', 'opinion',
    'opposite', 'orange', 'ordinary', 'organize', 'origin', 'original', 'outcome', 'outdoor', 'outside', 'overcome',
    'package', 'painful', 'paradise', 'parent', 'partner', 'passion', 'patient', 'pattern', 'peaceful', 'perfect',
    'perform', 'period', 'pioneer', 'planet', 'pleasant', 'pleasure', 'pocket', 'poetry', 'popular', 'portion',
    'positive', 'powder', 'practice', 'prepare', 'present', 'pretend', 'prevent', 'primary', 'printer', 'private',
    'process', 'produce', 'project', 'promise', 'protect', 'provide', 'public', 'publish', 'puzzle', 'quantity',
    'quarter', 'quickly', 'rather', 'reader', 'reason', 'receive', 'recent', 'recipe', 'recover', 'reflect',
    'regard', 'region', 'regular', 'related', 'release', 'remain', 'remind', 'remote', 'remove', 'repeat',
    'replace', 'report', 'request', 'require', 'respect', 'respond', 'result', 'return', 'reveal', 'reverse',
    'review', 'reward', 'rhythm', 'romance', 'routine', 'sample', 'satisfy', 'scatter', 'scenery', 'schedule',
    'seldom', 'select', 'sentence', 'serious', 'service', 'settle', 'several', 'shadow', 'shallow', 'shelter',
    'shortly', 'shoulder', 'silence', 'silver', 'simple', 'sincere', 'single', 'situate', 'sixteen', 'society',
    'soldier', 'someone', 'species', 'specify', 'statue', 'stomach', 'storage', 'strange', 'stranger', 'strategy',
    'stronger', 'student', 'subject', 'succeed', 'success', 'suggest', 'summary', 'summer', 'sunshine', 'support',
    'suppose', 'surface', 'surprise', 'survive', 'suspect', 'sweater', 'symbol', 'talent', 'telephone', 'television',
    'terrible', 'therefore', 'thinking', 'thousand', 'thunder', 'tomorrow', 'tonight', 'tornado', 'towards', 'traffic',
    'transfer', 'transform', 'travel', 'treasure', 'trouble', 'typical', 'uncover', 'uniform', 'unless', 'unusual',
    'upstairs', 'useful', 'vacation', 'valley', 'variety', 'vehicle', 'venture', 'version', 'vintage', 'violent',
    'virtual', 'visible', 'visitor', 'volcano', 'voyage', 'warning', 'website', 'weekend', 'western', 'whatever',
    'whether', 'willing', 'window', 'winter', 'wisdom', 'wonder', 'worker', 'workshop', 'worried', 'writing',
    'yellow',
  ],
  hard: [
    'awkward', 'juxtapose', 'bureaucracy', 'conscientious', 'unequivocally', 'quintessential', 'onomatopoeia', 'kaleidoscope', 'labyrinthine', 'idiosyncratic',
    'perpendicular', 'entrepreneurship', 'exquisite', 'sphinx', 'zephyr', 'gnarly', 'psychology', 'mnemonic', 'phlegm', 'squawk',
    'jinx', 'fjord', 'lymph', 'crypt', 'glyph', 'wryly', 'syzygy', 'twelfth', 'strengths', 'sixths',
    'nymphs', 'schnapps', 'asymmetric', 'buoyancy', 'catastrophe', 'dexterity', 'euphemism', 'flabbergasted', 'gregarious', 'hierarchy',
    'inconceivable', 'jubilant', 'knowledgeable', 'lieutenant', 'malfeasance', 'nonchalant', 'obfuscate', 'paradoxical', 'quizzical', 'reverberate',
    'serendipity', 'tumultuous', 'ubiquitous', 'vicissitude', 'whimsical', 'xylophone', 'yacht', 'zealous', 'abbreviate', 'abrupt',
    'absurd', 'abyss', 'accommodate', 'acquiesce', 'acquire', 'aesthetic', 'aggravate', 'allegiance', 'ambiguous', 'anemone',
    'annihilate', 'anomaly', 'apocalypse', 'apparatus', 'archipelago', 'asphalt', 'asthma', 'auspicious', 'bourgeois', 'broccoli',
    'bureaucrat', 'cacophony', 'camouflage', 'caribbean', 'cataclysm', 'cemetery', 'chauffeur', 'chrysanthemum', 'clandestine', 'coalesce',
    'colloquial', 'colonel', 'commemorate', 'conscience', 'connoisseur', 'consensus', 'convalesce', 'cylinder', 'debacle', 'demagogue',
    'desiccate', 'diaphragm', 'dilettante', 'disastrous', 'discern', 'draconian', 'ebullient', 'eccentric', 'effervescent', 'efficacious',
    'egregious', 'eloquent', 'embezzle', 'enigma', 'ephemeral', 'epitome', 'equilibrium', 'erroneous', 'esophagus', 'espionage',
    'exacerbate', 'exhilarate', 'exorbitant', 'facetious', 'fahrenheit', 'fallacy', 'fluorescent', 'forfeit', 'fuchsia', 'gauge',
    'gauche', 'genealogy', 'gnaw', 'guttural', 'handkerchief', 'harass', 'hemorrhage', 'heinous', 'hippopotamus', 'hors',
    'hyperbole', 'hypocrisy', 'ideosyncrasy', 'immaculate', 'impeccable', 'inconspicuous', 'indict', 'inept', 'inoculate', 'insidious',
    'intrepid', 'irascible', 'jeopardy', 'juggernaut', 'kayak', 'khaki', 'liaison', 'licorice', 'maelstrom', 'maintenance',
    'manoeuvre', 'masquerade', 'mediocre', 'memento', 'millennium', 'millionaire', 'minuscule', 'mischievous', 'misspell', 'narcissus',
    'nauseous', 'necessary', 'nemesis', 'nuance', 'obsequious', 'occurrence', 'ominous', 'ostracize', 'palette', 'panacea',
    'paradigm', 'parallel', 'paraphernalia', 'pastiche', 'penicillin', 'perennial', 'perseverance', 'pharaoh', 'plagiarize', 'plateau',
    'playwright', 'pneumonia', 'poignant', 'precocious', 'presumptuous', 'privilege', 'pronunciation', 'quandary', 'quarantine', 'questionnaire',
    'quixotic', 'raspberry', 'recommend', 'reconnaissance', 'renaissance', 'rendezvous', 'repertoire', 'resilient', 'resuscitate', 'sacrilegious',
    'scintillate', 'scissors', 'sergeant', 'silhouette', 'simultaneous', 'solstice', 'soliloquy', 'sophomore', 'sovereign', 'specimen',
    'spontaneous', 'succinct', 'supersede', 'surveillance', 'susceptible', 'synonymous', 'threshold', 'tranquil', 'turquoise', 'unanimous',
    'unwieldy', 'vacuum', 'vehement', 'vengeance', 'ventriloquist', 'vociferous', 'voluminous', 'wednesday', 'wield', 'zealot',
    'zucchini',
  ],
};

// Common punctuation-ish symbols used by the "punctuation" mode to sprinkle
// realistic marks between words.
export const PUNCTUATION = [',', '.', '.', '.', ';', ':', '?', '!', '—'];
